#!/usr/bin/env bash
# Install nginx server
#Nginx should be listening on port 80
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx start
