#!/usr/bin/env bash
# Install nginx server
#Nginx should be listening on port 80
apt-get -y update
apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx start
